name: manage-azure-policy-2e5f16a2
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'LAB/policies/Add_a_tag_to_resources_4f9dc7db-30c1-420c-b61a-e1d640128d26/**'
#      - .github/workflows/manage-azure-policy-2e5f16a2.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_2e5f16a2}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          LAB/policies/Add_a_tag_to_resources_4f9dc7db-30c1-420c-b61a-e1d640128d26/**
